name: Examples (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Check examples
      run: cargo check --manifest-path examples/Cargo.toml --all-targets --verbose

    - name: Run clippy
      run: cargo clippy --manifest-path examples/Cargo.toml --all-targets -- -D clippy::all

    - name: Run rustfmt
      run: cargo fmt --manifest-path examples/Cargo.toml --check
